# Generated by Django 5.2.11 on 2026-02-20 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabelTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("width_mm", models.DecimalField(decimal_places=2, max_digits=6)),
                ("height_mm", models.DecimalField(decimal_places=2, max_digits=6)),
                ("background_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LabelElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element_type",
                    models.CharField(
                        choices=[
                            ("barcode_128", "Barcode (Code 128)"),
                            ("qr_code", "QR Code"),
                            ("asset_name", "Asset Name"),
                            ("category_name", "Category Name"),
                            ("barcode_text", "Barcode Text"),
                            ("logo", "Logo"),
                            ("static_text", "Static Text"),
                        ],
                        max_length=20,
                    ),
                ),
                ("x_mm", models.DecimalField(decimal_places=2, max_digits=6)),
                ("y_mm", models.DecimalField(decimal_places=2, max_digits=6)),
                ("width_mm", models.DecimalField(decimal_places=2, max_digits=6)),
                ("height_mm", models.DecimalField(decimal_places=2, max_digits=6)),
                ("rotation", models.IntegerField(default=0)),
                (
                    "font_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("helvetica", "Helvetica"),
                            ("courier", "Courier"),
                            ("liberation_sans", "Liberation Sans"),
                            ("liberation_mono", "Liberation Mono"),
                            ("dejavu_sans", "DejaVu Sans"),
                            ("dejavu_mono", "DejaVu Sans Mono"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "font_size_pt",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("font_bold", models.BooleanField(default=False)),
                (
                    "text_align",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Centre"),
                            ("right", "Right"),
                        ],
                        default="left",
                        max_length=10,
                    ),
                ),
                ("max_chars", models.IntegerField(blank=True, null=True)),
                ("static_content", models.TextField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="printing.labeltemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
