# Generated by Django 5.2.11 on 2026-02-20 04:52

from django.db import migrations


def create_default_template(apps, schema_editor):
    LabelTemplate = apps.get_model("printing", "LabelTemplate")
    LabelElement = apps.get_model("printing", "LabelElement")

    template = LabelTemplate.objects.create(
        name="Square 62x62mm",
        width_mm=62,
        height_mm=62,
        background_color="#FFFFFF",
        is_default=True,
    )

    # Asset name at top, centred
    LabelElement.objects.create(
        template=template,
        element_type="asset_name",
        x_mm=2,
        y_mm=1,
        width_mm=58,
        height_mm=5,
        font_name="helvetica",
        font_size_pt=7,
        font_bold=True,
        text_align="center",
        max_chars=20,
        sort_order=1,
    )

    # QR code centred in middle
    LabelElement.objects.create(
        template=template,
        element_type="qr_code",
        x_mm=6,
        y_mm=7,
        width_mm=50,
        height_mm=50,
        sort_order=2,
    )

    # Barcode text at bottom, centred
    LabelElement.objects.create(
        template=template,
        element_type="barcode_text",
        x_mm=2,
        y_mm=57,
        width_mm=58,
        height_mm=4,
        font_name="courier",
        font_size_pt=5,
        text_align="center",
        sort_order=3,
    )


def remove_default_template(apps, schema_editor):
    LabelTemplate = apps.get_model("printing", "LabelTemplate")
    LabelTemplate.objects.filter(name="Square 62x62mm").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0002_propsconnection_printer_printjob"),
    ]

    operations = [
        migrations.RunPython(create_default_template, remove_default_template),
    ]
