# Generated by Django 5.2.11 on 2026-02-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0003_create_default_square_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="printjob",
            name="qr_content",
            field=models.URLField(
                blank=True,
                help_text="URL to encode in QR code. If blank, uses the barcode string.",
                null=True,
            ),
        ),
    ]
