# Generated by Django 5.2.11 on 2026-02-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0004_add_qr_content_to_printjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="printjob",
            name="department_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="printjob",
            name="site_short_name",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
