# Generated by Django 5.2.11 on 2026-02-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0005_printjob_department_name_printjob_site_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labelelement",
            name="element_type",
            field=models.CharField(
                choices=[
                    ("barcode_128", "Barcode (Code 128)"),
                    ("qr_code", "QR Code"),
                    ("asset_name", "Asset Name"),
                    ("category_name", "Category Name"),
                    ("department_name", "Department Name"),
                    ("site_short_name", "Site Short Name"),
                    ("barcode_text", "Barcode Text"),
                    ("logo", "Logo"),
                    ("static_text", "Static Text"),
                ],
                max_length=20,
            ),
        ),
    ]
