# Generated by Django 5.2.11 on 2026-02-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0006_alter_labelelement_element_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propsconnection",
            name="server_url",
            field=models.CharField(
                help_text="PROPS server hostname or URL (e.g. props.example.com)",
                max_length=200,
            ),
        ),
    ]
