# Generated by Django 5.2.11 on 2026-02-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0007_alter_propsconnection_server_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="printer",
            name="printer_type",
            field=models.CharField(
                choices=[
                    ("tcp", "TCP (Network Printer)"),
                    ("virtual", "Virtual (Save PDF)"),
                ],
                default="tcp",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="printer",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
