# Generated by Django 5.2.11 on 2026-02-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0008_printer_printer_type_alter_printer_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="printjob",
            name="output_file",
            field=models.FileField(
                blank=True,
                help_text="PDF output file (populated for virtual printer jobs).",
                null=True,
                upload_to="labels/",
            ),
        ),
    ]
