# Generated by Django 5.2.11 on 2026-02-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0009_printjob_output_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="printjob",
            name="label_type",
            field=models.CharField(
                choices=[("asset", "Asset"), ("location", "Location")],
                default="asset",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="printjob",
            name="location_categories",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="printjob",
            name="location_departments",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="printjob",
            name="location_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="printjob",
            name="location_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="labelelement",
            name="element_type",
            field=models.CharField(
                choices=[
                    ("barcode_128", "Barcode (Code 128)"),
                    ("qr_code", "QR Code"),
                    ("asset_name", "Asset Name"),
                    ("category_name", "Category Name"),
                    ("department_name", "Department Name"),
                    ("site_short_name", "Site Short Name"),
                    ("barcode_text", "Barcode Text"),
                    ("logo", "Logo"),
                    ("static_text", "Static Text"),
                    ("location_name", "Location Name"),
                    ("location_description", "Location Description"),
                    ("location_categories", "Location Categories"),
                    ("location_departments", "Location Departments"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="printjob",
            name="asset_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="printjob",
            name="barcode",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="printjob",
            name="category_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
