# Generated by Django 5.2.11 on 2026-02-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0010_printjob_label_type_printjob_location_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labelelement",
            name="element_type",
            field=models.CharField(
                choices=[
                    ("barcode_128", "Barcode (Code 128)"),
                    ("qr_code", "QR Code"),
                    ("asset_name", "Asset Name"),
                    ("category_name", "Category Name"),
                    ("department_name", "Department Name"),
                    ("site_short_name", "Site Short Name"),
                    ("barcode_text", "Barcode Text"),
                    ("logo", "Logo"),
                    ("static_text", "Static Text"),
                    ("location_name", "Location Name"),
                    ("location_description", "Location Description"),
                    ("location_categories", "Location Categories"),
                    ("location_departments", "Location Departments"),
                ],
                max_length=30,
            ),
        ),
    ]
