# Generated by Django 5.2.11 on 2026-02-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0011_alter_labelelement_element_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="printer",
            name="cups_queue",
            field=models.CharField(
                blank=True,
                help_text="CUPS printer queue name (e.g. DYMO_LabelWriter_5XL)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="printer",
            name="printer_type",
            field=models.CharField(
                choices=[
                    ("tcp", "TCP (Network Printer)"),
                    ("cups", "CUPS (System Printer)"),
                    ("virtual", "Virtual (Save PDF)"),
                ],
                default="tcp",
                max_length=20,
            ),
        ),
    ]
